=== Carlos5Noob/ejsXML/t02/dtd/nota.dtd
<!ELEMENT nota (fecha, urgente?, de, para+, (asunto|texto) )>

<!ELEMENT fecha (dia, hora)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

<!ELEMENT urgente EMPTY>
<!ELEMENT de (#PCDATA)>

<!ATTLIST de id CDATA #IMPLIED>

<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT texto (#PCDATA)>

<!ATTLIST texto idioma (es|en) #IMPLIED>


<!ATTLIST nota leido CDATA "no"
               borrar (si|no) #IMPLIED>

<!ATTLIST para id ID #REQUIRED>

=== Carlos5Noob/ejsXML/t02/dtd/nota.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nota SYSTEM "nota.dtd">
<nota leido="no" borrar="si">
  <fecha>
    <dia>Lunes</dia>
    <hora>3:33</hora>
  </fecha>
  <urgente/> <!-- es opcional -->
  <de id="A123">Ana</de>  
  <para id="B123">Luis</para>
  <para id="C123">Alfredo</para>
  <texto idioma="es">Te recuerdo que mañana tenemos reunión a las 14:00 para bla, bla, bla..</texto>
</nota>
